import CustomImage from '../../../common/CustomImage';
import { FlexBox } from '../../../common/FlexBox';
import * as S from './index.styled';
import { BsArrowRight } from "react-icons/bs";

const TakeStep = () => {
  return (
    <S.TakeStepStyle >
      <S.Container>
        <FlexBox marginBottom='180px' smMarginBottom='40px'>
          <S.TakeStepFlex data-aos="fade-up" data-aos-anchor-placement="bottom-bottom"  data-aos-duration="2000">
            <S.Title>
              Take your first step into the new vision of stable rewards!
            </S.Title>
            <S.ContentText>
              Our system is an optimised economic model that uses the fees generated by the protocol in the most optimal way. <br />
              Paying out the generated protocol fees to stakers through an ecosystem booster token(xQUTM), which prevents inflation and distribute the rewards in ETH tokens.
            </S.ContentText>
            <S.GetStartedButton>
              Get Started
            </S.GetStartedButton>
          </S.TakeStepFlex>
          <S.CoinSection data-aos="fade-up-right">
            <CustomImage
              image="/assets/images/coins/Tether.svg"
              position='absolute'
              top='0px'
              right='100px'
            />
            <CustomImage
              image="/assets/images/coins/injtoken.png"
              position='absolute'
              top='180px'
              right='30px'
              width='219px'
              height='171px'
            />
            <CustomImage
              image="/assets/images/coins/USDC.svg"
              position='absolute'
              top='170px'
              right='300px'
            />
            <CustomImage
              image="/assets/images/coins/Quantum.svg"
              position='absolute'
              top='300px'
              right='140px'
            />
          </S.CoinSection>
        </FlexBox>

        <S.JoinCommunity data-aos="zoom-in" data-aos-duration="1500">
          <S.JoinCommunityTitle>
            Join our Community now!
          </S.JoinCommunityTitle>
          <S.JoinCommunitySubTitle>
            Our Alpha Campaign is live! Join now.
          </S.JoinCommunitySubTitle>
          <S.QuantumAlpha href = "https://twitter.com/QuantumFi_" target='__blank'>
            Quantum Alpha
            <BsArrowRight color="white" />
          </S.QuantumAlpha>
        </S.JoinCommunity>
      </S.Container>
    </S.TakeStepStyle>
  );
};

export default TakeStep;
